### ISSUE TITLE
Package for PyPI

### ISSUE THREAD

**Issue by xiongchiamiov** [ioerror/blockfinder#80]
If we package blockfinder, then it's only a `pip install blockfinder` away; plus, it introduces an update mechanism tied into one of the system-wide installers, which is always nice.

Since this involves moving around all the code, I'd like to wait until #74 is merged to avoid unnecessary conflict headaches, but I figured I'd ask you guys if there were any reasons you hadn't done this yet (other than time and general busyness).

**Comment by d1b** [comment]
@xiongchiamiov I hope to resolve this issue soon :-)

**Comment by xiongchiamiov** [comment]
It looks like this was packaged in #88, but [isn't published to PyPI yet](https://pypi.python.org/pypi?%3Aaction=search&term=blockfinder&submit=search)?

**Comment by d1b** [comment]
@xiongchiamiov correct. I have uploaded a 'dev' version to PyPi we need to do slightly more work to detail how to use it when it is installed as a python package through pip.

**Comment by d1b** [comment]
I have uploaded blockfinder 4.0.0 to pypi.
